# **📝Exercícios de 1 - 10:**

In [20]:
# EXERCÍCIO 1:  Import numpy as np and print the version number.
import numpy as np
print(f"NumPy version: {np.__version__}")

# EXERCÌCIO 2: Create a 1D array of numbers from 0 to 9.
array = np.arange(10)
print(array)

# EXERCÌCIO 3: Create a 3×3 numpy array of all True values.
array1 = np.full((3, 3), True, dtype= bool)
print(array1)

# EXERCÌCIO 4: Extract all odd numbers from arr.
array2 = array[array % 2 == 1]
print(array2)

# EXERCÌCIO 6: Substitua todos os números ímpares por -1 sem modificar o original
#COMO EU FIZ:
array_modificado = array.copy()
array_modificado[array_modificado % 2 == 1] = -1
print(array_modificado)

#COMO RESPONDERAM NO SITE:
mod = np.where(array % 2 == 1, -1, array)
print(mod)

# EXERCÌCIO 5: Substitua todos os números ímpares por -1
array[array % 2 == 1] = -1
print(array)

# EXERCÌCIO 7: Converta o array 1D em um array 2D com 2 linhas
#como eu fiz:
array4 = np.arange(10).reshape(2, 5)
print(array4)

#como estava no gabarito:
array = np.arange(10)
mod1 = array.reshape(2, -1) #o -1 faz o nupyescolher autoaticamente o número de colunas
print(mod1)

# EXERCÌCIO 8: Empilhe arrays e verticalmente
a = np.arange(10).reshape(2, 5)
b = np.repeat(1, 10).reshape(2, 5)

empilhamento = np.vstack((a, b))
print(empilhamento)

# EXERCÌCIO 9: Empilhe arrays  horizontalmente.
empilhamento = np.hstack((a, b))
print(empilhamento)

# EXERCÍCIO 10: Usando apenas funções numpy e o array de entrada , produz um array que primeiro repete cada elemento 3 vezes, depois faz tile em todo o array 3 vezes
a = np.array([1,2,3])
b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(b)


NumPy version: 2.0.2
[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
