# **📝Exercícios de 1 - 10:**


In [ ]:
# EXERCÍCIO 1:  Import numpy as np and print the version number.
import numpy as np
print(f"NumPy version: {np.__version__}")

# EXERCÌCIO 2: Create a 1D array of numbers from 0 to 9.
array = np.arange(10)
print(array)

# EXERCÌCIO 3: Create a 3×3 numpy array of all True values.
array1 = np.full((3, 3), True, dtype= bool)
print(array1)

# EXERCÌCIO 4: Extract all odd numbers from arr.
array2 = array[array % 2 == 1]
print(array2)

# EXERCÌCIO 6: Substitua todos os números ímpares por -1 sem modificar o original
#COMO EU FIZ:
array_modificado = array.copy()
array_modificado[array_modificado % 2 == 1] = -1
print(array_modificado)

#COMO RESPONDERAM NO SITE:
mod = np.where(array % 2 == 1, -1, array)
print(mod)

# EXERCÌCIO 5: Substitua todos os números ímpares por -1
array[array % 2 == 1] = -1
print(array)

# EXERCÌCIO 7: Converta o array 1D em um array 2D com 2 linhas
#como eu fiz:
array4 = np.arange(10).reshape(2, 5)
print(array4)

#como estava no gabarito:
array = np.arange(10)
mod1 = array.reshape(2, -1) #o -1 faz o nupyescolher autoaticamente o número de colunas
print(mod1)

# EXERCÌCIO 8: Empilhe arrays e verticalmente
a = np.arange(10).reshape(2, 5)
b = np.repeat(1, 10).reshape(2, 5)

empilhamento = np.vstack((a, b))
print(empilhamento)

# EXERCÌCIO 9: Empilhe arrays  horizontalmente.
empilhamento = np.hstack((a, b))
print(empilhamento)

# EXERCÍCIO 10: Usando apenas funções numpy e o array de entrada , produz um array que primeiro repete cada elemento 3 vezes, depois faz tile em todo o array 3 vezes
a = np.array([1,2,3])
b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(b)


NumPy version: 2.0.2
[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# **📝Exercícios de 11 - 21:**

In [ ]:
# EXERCÌCIO 11: Encontre os itens comuns entre arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intercesao = np.intersect1d(a, b)
print(intercesao)

# EXERCÌCIO 12: Remover itens presentes em outro array
diferenca = np.setdiff1d(a, b)
print(diferenca)

#EXERCÍCIO 13: Encontrar posições onde dois arrays coincidem
igualdade_de_indicies = np.where( a == b)
print(igualdade_de_indicies[0])

# EXERCÍCIO 14:  Extrair números dentro de um determinado intervalo
a[(a>0) & (a <= 6)]

# EXERCÍCIO 15: Vetorizar uma função escalar para trabalhar em arrays
def maxx(x, y):

    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Para retornar os números (o máximo entre a e b em cada posição)
maximo = np.where(a >= b, a, b)
print(maximo)
                 #ou
maximo2 = np.vectorize(maxx)
print(maximo2(a, b))

# EXERCÍCIO 16: Trocar duas colunas em um array 2D
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3[:, [1,2]] = array3[:, [2, 1]]
print(array3)

# EXERCÍCIO 17: Trocar duas linhas em um array 2D
troca_linha = array3[[2, 0, 1], :]
print(troca_linha)

# EXERCÍCIO 18: Reverter as Linhas de um Array 2D
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
inverterlinhas_array = array3[:, ::-1]
print(inverter_array)

# EXERCÌCIO 19: Reverter as Colunas de um Array 2D
inverter_colunas = array3[::-1, :]
print(inverter_colunas)

# EXERCÍCIO 20: Criar um array 2D de flutuadores aleatórios entre 5 e 10
array5 = np.random.uniform(low=5.0, high=10.0, size=(5, 3))
print(array5)

# EXERCÍCIO 21: Imprimir apenas 3 casas decimais
array6 = np.random.random(size=(5,3))
print(np.round(array6, 3))

[2 4]
[1 3 5 6]
[1 3 5 7]
[6 7 9 8 9 7 5]
[6 7 9 8 9 7 5]
[[1 3 2]
 [4 6 5]
 [7 9 8]]
[[7 9 8]
 [1 3 2]
 [4 6 5]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[9.47891254 5.27149524 7.47258241]
 [5.24198585 9.3676641  7.08682048]
 [5.9280373  9.43140776 5.91362677]
 [7.46590019 8.48380474 8.23346275]
 [8.61080629 7.49871761 7.87100793]]
[[0.701 0.798 0.882]
 [0.269 0.823 0.791]
 [0.789 0.148 0.595]
 [0.425 0.936 0.73 ]
 [0.545 0.909 0.734]]
